'use strict';
// Chapter titles and FAR1–FAR5 grouping transcribed from the three user screenshots.
const FAR_CHAPTERS=[
 [1,'FAR1','財務会計の基本的概念と財務諸表','Basic Concepts of Financial Accounting and Financial Statements',['Financial Statements']],
 [2,'FAR1','財務諸表の表示と開示・認識と測定の概念','Presentation and Disclosure of Financial Statements and Concepts of Recognition and Measurement',[]],
 [3,'FAR1','流動資産（現金・売掛金・棚卸資産）','Current Assets (Cash, Accounts Receivable, Inventory)',['Cash','Accounts Receivable','Inventory']],
 [4,'FAR1','流動負債と偶発事象','Current Liabilities and Contingencies',['Liabilities']],
 [5,'FAR2','有形固定資産','Property, Plant, and Equipment',['PPE']],
 [6,'FAR2','無形資産','Intangible Assets',['Intangible Assets']],
 [7,'FAR2','貨幣の時間価値','Time Value of Money',[]],
 [8,'FAR2','社債','Bonds',['Bonds']],
 [9,'FAR2','借手のリース会計','Lease Accounting for Lessee',['Leases']],
 [10,'FAR2','受取手形と支払手形','Notes Receivable and Payable',[]],
 [11,'FAR3','顧客との契約に基づく収益の認識','Revenue from Contracts with Customers',['Revenue']],
 [12,'FAR3','資本取引と1株当たり利益','Equity Transactions and Earnings Per Share',['Equity','EPS']],
 [13,'FAR4','投資','Investments',[]],
 [14,'FAR4','連結財務諸表の作成と企業結合後の調整','Preparation of Consolidated Financial Statements and Adjustments Subsequent to Combination',['Consolidation']],
 [15,'FAR4','税効果会計','Deferred Taxes',[]],
 [16,'FAR4','キャッシュ・フロー計算書','Statement of Cash Flows',['Statement of Cash Flows']],
 [17,'FAR4','会計上の変更と誤謬の修正','Accounting Changes and Error Corrections',['Accounting Changes']],
 [18,'FAR4','その他のトピック','Miscellaneous Topics',[]],
 [19,'FAR4','財務指標と経営指標','Financial Statement Ratios and Performance Metrics',[]],
 [20,'FAR5','非政府系の非営利組織','Nongovernmental Not-for-profit Organizations',['NFP Accounting']],
 [21,'FAR5','政府会計','Governmental Accounting',['Governmental Accounting']]
].map(([chapter,unit,japanese,english,aliases])=>({id:`far-chapter-${String(chapter).padStart(2,'0')}`,chapter,unit,japanese,english,aliases,name:`Chapter ${chapter} · ${english}`}));
function initialFarChapters(){return FAR_CHAPTERS.map(({aliases,...c})=>({...c,rating:'C',accuracy:null,last:'',count:0,note:'',estimatedMinutes:farSourceMinutes(c.chapter),priorStudyMinutes:0}));}
function migrateFarChapters(s){
 if(s.farMapVersion===1){
  if(s.far.length!==21||FAR_CHAPTERS.some(c=>!s.far.some(f=>f.id===c.id)))throw Error('FAR章データが不正です');
  if(s.farLegacyArchive!==undefined&&!Array.isArray(s.farLegacyArchive))throw Error('FAR旧記録が不正です');
  return migrateFarWorkload(s);
 }
 // Never discard the old records, even where a one-to-one chapter match is ambiguous.
 const previous=JSON.parse(JSON.stringify(s.far));
 s.farLegacyArchive=[...(s.farLegacyArchive||[]),...previous];
 const idMap=new Map(),rows=initialFarChapters();
 for(const c of FAR_CHAPTERS){
  const old=previous.filter(f=>f.id===c.id||f.name===c.name||f.name===c.english||c.aliases.includes(f.name)),row=rows.find(r=>r.id===c.id);
  old.forEach(f=>idMap.set(f.id,c.id));
  if(!old.length)continue;
  row.legacyIds=old.map(f=>f.id);
  if(old.length===1){const f=old[0];for(const key of ['rating','accuracy','last','count','note','estimatedMinutes','priorStudyMinutes'])if(f[key]!==undefined)row[key]=f[key];}
  else{
   row.rating=old.some(f=>f.rating==='C')?'C':old.some(f=>f.rating==='B')?'B':'A';
   row.accuracy=null;row.count=Math.max(...old.map(f=>Number(f.count)||0));
   row.last=old.map(f=>f.last||'').sort().at(-1)||'';
   row.note='複数の旧論点を統合しました。評価は最も低い評価、最終学習日は最新、学習回数は最大値を仮採用しています。章全体の正答率は未設定です。旧記録を確認して調整してください。';
   row.note+='\n'+old.filter(f=>f.note).map(f=>`${f.name}：${f.note}`).join('\n');
  }
 }
 const remap=ids=>[...new Set(ids.map(id=>idMap.get(id)||id))];
 for(const t of s.tasks){
  if(Array.isArray(t.farTopicIds))t.farTopicIds=remap(t.farTopicIds);
  else if(t.autoGenerated&&t.category==='USCPA'){
   const names=t.name.split(' · ').slice(1).join(' · ').split(' / ');
   t.farTopicIds=remap(previous.filter(f=>names.includes(f.name)).map(f=>f.id));
  }
 }
 for(const r of Object.values(s.planner?.history||{}))if(Array.isArray(r.farTopicIds))r.farTopicIds=remap(r.farTopicIds);
 s.far=rows;s.farMapVersion=1;return migrateFarWorkload(s);
}
function farRecordsTable(rows,archived=false){return `<div class="scroll"><table class="far-table"><thead><tr><th>章・論点</th>${archived?'':'<th>必要時間・進捗</th>'}<th>習熟度</th><th>MCQ正答率</th><th>最終学習日</th><th>学習回数</th><th>${archived?'メモ':'記録'}</th></tr></thead><tbody>${rows.map(f=>`<tr><td class="far-title">${f.chapter?`<span class="badge">Chapter ${f.chapter}</span><strong>${esc(f.japanese)}</strong><span class="muted">${esc(f.english)}</span>`:esc(f.name)}</td>${archived?'':`<td data-label="必要時間・進捗">${farStudyDetails(f)}</td>`}<td data-label="習熟度">${esc(f.rating)}</td><td data-label="MCQ正答率">${f.accuracy===null||f.accuracy===''?'未設定':`${esc(f.accuracy)}%`}</td><td data-label="最終学習日">${esc(f.last||'—')}</td><td data-label="学習回数">${esc(f.count)}</td><td data-label="${archived?'メモ':'記録'}">${archived?esc(f.note||'—'):button('edit-far','記録',f.id,'compact')}</td></tr>`).join('')}</tbody></table></div>`;}
function renderFarChapters(){return `<section class="panel"><h2>FAR 論点マップ · 全21章</h2><p class="muted">添付教材のChapter順・FAR1〜FAR5に対応しています。A：覚えている　B：少し曖昧　C：ほぼ忘れている</p><p class="muted">Daily Plannerはこの章立てで重点論点を順送りします。作成済みタスクの内容・実績は変更しません。</p></section>${spacedReviewPanel()}${farWorkloadSummary()}${['FAR1','FAR2','FAR3','FAR4','FAR5'].map(unit=>`<section class="panel far-unit"><h2>${unit}</h2>${farRecordsTable(state.far.filter(f=>f.unit===unit))}</section>`).join('')}${state.farLegacyArchive?.length?`<details class="panel"><summary>移行前の学習記録（${state.farLegacyArchive.length}件）</summary><p class="muted">旧データをそのまま保存しています。Cash・Accounts Receivable・InventoryはChapter 3、Equity・EPSはChapter 12へ統合しました。統合時の仮採用値は各章のメモに記載しています。</p>${farRecordsTable(state.farLegacyArchive,true)}</details>`:''}`;}
