'use strict';
// Japanese public holidays and substitute holidays, Cabinet Office (2026–2027).
// https://www8.cao.go.jp/chosei/shukujitsu/gaiyou.html
const JP_STUDY_HOLIDAYS=new Set([
 ...'01-01 01-12 02-11 02-23 03-20 04-29 05-03 05-04 05-05 05-06 07-20 08-11 09-21 09-22 09-23 10-12 11-03 11-23'.split(' ').map(d=>'2026-'+d),
 ...'01-01 01-11 02-11 02-23 03-21 03-22 04-29 05-03 05-04 05-05 07-19 08-11 09-20 09-23 10-11 11-03 11-23'.split(' ').map(d=>'2027-'+d)
]);
function defaultWeekdayMinutes(source,day){return day===0||day===6?300:source.settings.target;}
const WEEKDAY_LABELS=['日','月','火','水','木','金','土'];
const clonePlanning=value=>JSON.parse(JSON.stringify(value));
function migratePlanningTools(s){
 const p=s.planner;
 if(p.weeklyMinutes===undefined)p.weeklyMinutes=Array(7).fill(null);
 if(!Array.isArray(p.weeklyMinutes)||p.weeklyMinutes.length!==7||p.weeklyMinutes.some(n=>n!==null&&(!Number.isInteger(n)||n<0||n>480)))throw Error('曜日別時間が不正です');
 if(p.holidayMinutes===undefined)p.holidayMinutes=300;
 if(!Number.isInteger(p.holidayMinutes)||p.holidayMinutes<0||p.holidayMinutes>480)throw Error('祝日の学習時間が不正です');
 if(p.dateMinutes===undefined)p.dateMinutes={};
 if(!p.dateMinutes||typeof p.dateMinutes!=='object'||Array.isArray(p.dateMinutes)||Object.entries(p.dateMinutes).some(([d,n])=>!validDate(d)||!Number.isInteger(n)||n<0||n>480))throw Error('日別時間が不正です');
 if(p.replans===undefined)p.replans=[];
 if(!Array.isArray(p.replans)||p.replans.some(r=>!r||!validDate(r.date)||!validDate(r.at?.slice(0,10))||!Number.isInteger(r.limit)||r.limit<0||r.limit>480||!Array.isArray(r.removed)||r.removed.some(t=>!t||typeof t.id!=='string'||typeof t.name!=='string'||!Number.isFinite(t.minutes)||t.minutes<0)||!Array.isArray(r.addedIds)||r.addedIds.some(id=>typeof id!=='string')))throw Error('再配分履歴が不正です');
 if(s.settings.backup===undefined)s.settings.backup={enabled:true,intervalDays:7,lastExported:'',snoozedUntil:''};
 const b=s.settings.backup;
 if(!b||typeof b.enabled!=='boolean'||![3,7,14,30].includes(b.intervalDays)||![b.lastExported,b.snoozedUntil].every(d=>d===''||validDate(d)))throw Error('バックアップ設定が不正です');
 for(const t of s.tasks){if(t.autoPlanOriginal!==undefined&&typeof t.autoPlanOriginal!=='string')throw Error('自動タスクの初期値が不正です');if(t.userEdited!==undefined&&typeof t.userEdited!=='boolean')throw Error('タスク編集状態が不正です');}
 for(const t of s.tasks)if(t.studyParts!==undefined){
  if(!Array.isArray(t.studyParts)||!t.studyParts.length||t.studyParts.some(p=>!p||typeof p.name!=='string'||!Number.isFinite(p.minutes)||p.minutes<=0||!dailyPlanTypes.includes(p.planType)||(p.farStudyChapterId!==undefined&&(!s.far.some(f=>f.id===p.farStudyChapterId)||typeof p.farStudyCredit!=='boolean'))))throw Error('学習内訳が不正です');
 }
 return s;
}
function scheduledMinutes(source,date=today()){
 const day=parse(date).getDay();
 return source.planner.dateMinutes?.[date]??(JP_STUDY_HOLIDAYS.has(date)?(source.planner.holidayMinutes??300):(source.planner.weeklyMinutes?.[day]??defaultWeekdayMinutes(source,day)));
}
function weeklyTarget(source,dates=weekDates()){return dates.reduce((n,d)=>n+dailyLimit(source,d),0);}
function taskPlanSignature(t){return JSON.stringify([t.name,t.category,t.date,t.deadline||'',t.minutes,t.priority||'中',t.note||'',...(t.studyParts?[JSON.stringify(t.studyParts)]:[])]);}
function isReplaceableTask(t,date,includeLegacy=false){
 return t.autoGenerated===true&&t.generatedFor===date&&t.date===date&&!t.done&&!(t.actual>0)&&!t.userEdited&&(t.autoPlanOriginal===undefined?includeLegacy:t.autoPlanOriginal===taskPlanSignature(t));
}
function buildReplan(source,date,minutes,includeLegacy=false){
 if(!validDate(date)||!Number.isInteger(minutes)||minutes<0||minutes>480)throw Error('今日の上限は0〜480分で入力してください。');
 if(date<source.planner.startDate)throw Error('学習開始日より前には再配分できません。');
 const candidate=validate(clonePlanning(source)),removed=candidate.tasks.filter(t=>isReplaceableTask(t,date,includeLegacy)),removedIds=new Set(removed.map(t=>t.id));
 candidate.tasks=candidate.tasks.filter(t=>!removedIds.has(t.id));
 candidate.planner.dateMinutes[date]=minutes;
 // Keep deleted/completed/edited slots blocked, including slots missing from today's visible list.
 const blockedIds=new Set([...(source.planner.history[date]?.taskIds||[]).filter(id=>!removedIds.has(id)),...candidate.tasks.map(t=>t.id)]);
 const added=buildDailyPlan(candidate,date,{replan:true,blockedIds});
 candidate.tasks.push(...added);
 const old=candidate.planner.history[date];
 candidate.planner.history[date]={version:2,planType:'daily-mixed',taskIds:[...new Set([...(old?.taskIds||[]),...added.map(t=>t.id)])],farTopicIds:inferFarTopicIds(candidate,date),limit:dailyLimit(candidate,date)};
 candidate.planner.replans.push({date,at:new Date().toISOString(),removed:clonePlanning(removed),addedIds:added.map(t=>t.id),limit:dailyLimit(candidate,date)});
 return {candidate,removed,added,kept:source.tasks.filter(t=>!removedIds.has(t.id)&&(t.date===date||(t.done&&t.completedDate===date)))};
}
function backupIsDue(source=state,date=today()){
 const b=source.settings.backup;
 return b.enabled&&(!b.snoozedUntil||date>=b.snoozedUntil)&&(!b.lastExported||date>=addDays(b.lastExported,b.intervalDays));
}
function backupReminder(){return backupIsDue()?`<section class="panel backup-reminder"><div class="section-head"><h2>バックアップの確認</h2>${button('export','JSONを書き出す')}</div><p class="muted">${state.settings.backup.lastExported?`最終書き出し操作：${esc(state.settings.backup.lastExported)}。新しい記録を保存しておきましょう。`:'バックアップの書き出し記録がありません。学習・出願データをJSONで保存できます。'}</p>${button('backup-snooze','明日知らせる','','compact')} <a href="#settings">通知の設定</a></section>`:'';}
function backupSettingsPanel(){
 const b=state.settings.backup;
 return `<section class="panel"><h2>バックアップ</h2><p>タスク・学習記録・出願・書類をJSONで保存できます。読み込みは現在のデータを置き換えます。</p><div class="toolbar">${button('export','JSONを書き出す')}<label>JSONを読み込む<input id="import" type="file" accept=".json,application/json"></label></div><h3>バックアップ通知</h3><p>最終書き出し操作：<strong>${esc(b.lastExported||'記録なし')}</strong></p><p>アプリ内の通知：${b.enabled?`${b.intervalDays}日ごと`:'OFF'}${b.snoozedUntil&&b.snoozedUntil>today()?` · ${esc(b.snoozedUntil)}まで延期`:''}</p><p class="muted">アプリを開いたときに表示します。ダウンロードの完了はブラウザで確認してください。過去の書き出し日は推測しません。</p>${button('backup-options','通知を変更')}</section>`;
}
function weeklySettingsPanel(){
 return `<section class="panel"><div class="section-head"><h2>曜日別の学習時間・休養日</h2>${button('weekly-options','変更する')}</div><div class="weekday-summary">${[1,2,3,4,5,6,0].map(i=>`<div><strong>${WEEKDAY_LABELS[i]}</strong><span>${state.planner.weeklyMinutes[i]===null?`標準 ${hours(Math.min(480,defaultWeekdayMinutes(state,i)))}`:state.planner.weeklyMinutes[i]===0?'休養日':hours(state.planner.weeklyMinutes[i])}</span></div>`).join('')}</div><p>日本の祝日：${hours(state.planner.holidayMinutes)}（2026〜2027年・振替休日を含む）</p><p class="muted">空欄は平日＝共通目標、土日＝5時間。0分は休養日です。祝日は曜日設定より優先し、日付ごとの設定が最優先です。自動作成は最大8時間、FAR受験前日は最大150分。変更済みの今日のプランは再配分の確認後に適用します。</p>${state.planner.dateMinutes[today()]!==undefined?`<p>今日だけの設定：${state.planner.dateMinutes[today()]}分（有効上限 ${dailyLimit(state)}分）</p>`:''}${button('replan-open','今日のプランを再配分')}${state.planner.replans.length?`<details><summary>最近の再配分履歴（${state.planner.replans.length}回）</summary>${state.planner.replans.slice(-5).reverse().map(r=>`<details><summary>${esc(r.date)} · 上限 ${esc(r.limit)}分 · 置換 ${r.removed.length}件</summary>${replanTaskRows(r.removed)}</details>`).join('')}</details>`:''}</section>`;
}
function openPlanningEditor(kind){
 if(loadFailed){alert('保存データの読み込みエラーを解決してから操作してください。');return;}
 edit={type:'planning-tools',kind};$('#form button[type=submit]').textContent=kind==='replan'?'変更内容を確認':'保存する';
 let html='';
 if(kind==='start-reset'){
  $('#dialog-title').textContent='開始日を設定・開始前のTo Doを削除';
  html=field('startDate','アプリの使用開始日','date',state.planner.subjectStarts.far||state.planner.startDate,null,'required')+'<p class="wide">指定日より前のTo Doは、完了済み・手動登録・繰越を含めて削除します。開始日前の保管履歴と再配分履歴も削除します。FAR・IELTSは指定日から開始し、面接・放送大学の開始日は保持します。次の画面で削除対象を確認できます。</p>';
  $('#form button[type=submit]').textContent='削除対象を確認';
 }else if(kind==='weekly'){
  $('#dialog-title').textContent='曜日別の学習時間';
  html='<p class="wide muted">空欄＝平日は共通目標、土日は5時間。0分＝休養日。祝日は曜日設定より優先します。各曜日の学習時間を0〜480分で指定できます。</p>'+[1,2,3,4,5,6,0].map(i=>field('day'+i,WEEKDAY_LABELS[i]+'曜日（分）','number',state.planner.weeklyMinutes[i]??'',null,'min="0" max="480" step="1"')).join('')+field('holidayMinutes','日本の祝日（分）','number',state.planner.holidayMinutes,null,'required min="0" max="480" step="1"');
 }else if(kind==='backup'){
  $('#dialog-title').textContent='バックアップ通知';const b=state.settings.backup;
  html=`<label class="wide"><span><input name="enabled" type="checkbox" ${b.enabled?'checked':''}> アプリ内でバックアップを知らせる</span></label>`+field('intervalDays','通知間隔','',b.intervalDays,[3,7,14,30].map(n=>[n,n+'日']));
 }else{
  $('#dialog-title').textContent='今日のプランを再配分';
  html=field('minutes','今日だけの学習上限（分・0なら休養日）','number',dailyLimit(state),null,'required min="0" max="480" step="1"')+`<p class="wide muted">未完了の自動タスクを再配分します。完了済み・手動登録・手動編集が記録されたタスク・別日からの繰越は保持します。削除済みのタスクは復活させません。変更は次の確認画面で適用するまで保存されません。</p><label class="wide"><span><input type="checkbox" name="includeLegacy"> 以前に作成した、編集履歴を判別できない自動タスクも再配分する</span></label><p class="wide muted">以前の自動タスクは初期状態の記録がないため、通常は保持します。上の項目を選ぶ場合は、次の画面の置き換え対象を確認してください。元のタスクは再配分履歴に残します。</p>`;
 }
 $('#fields').innerHTML=html;$('#editor').showModal();
}
function replanTaskRows(tasks){return tasks.length?`<ul class="replan-list">${tasks.map(t=>`<li><strong>${esc(t.name)}</strong><span>${esc(t.minutes)}分${t.done?' · 完了済み':''}</span>${t.note?`<details><summary>メモ</summary><p>${esc(t.note)}</p></details>`:''}</li>`).join('')}</ul>`:'<p class="muted">なし</p>';}
function showReplanPreview(data){
 const raw=localStorage.getItem(KEY),source=raw?validate(JSON.parse(raw)):validate(clonePlanning(state));
 const result=buildReplan(source,today(),Number(data.get('minutes')),data.has('includeLegacy'));
 edit={type:'planning-tools',kind:'replan-preview',raw,date:today(),...result};
 const before=dailyCommitted(source,today()),after=dailyCommitted(result.candidate,today()),limit=dailyLimit(result.candidate);
 $('#dialog-title').textContent='変更内容を確認';$('#form button[type=submit]').textContent='この内容で適用';
 $('#fields').innerHTML=`<div class="wide"><p>予定・実績確保：<strong>${before}分 → ${after}分</strong> / 新しい上限 ${limit}分</p>${after>limit?'<p class="warning">保持するタスクだけで上限を超えています。これらの時間は変更しません。</p>':''}<h3>置き換える未完了タスク（${result.removed.length}件）</h3>${replanTaskRows(result.removed)}<h3>新しく配分するタスク（${result.added.length}件）</h3>${replanTaskRows(result.added)}<details><summary>そのまま保持するタスク（${result.kept.length}件）</summary>${replanTaskRows(result.kept)}</details>${button('replan-back','条件を変更')}</div>`;
}
function submitPlanningTools(data){
 try{
  if(loadFailed)throw Error('保存データを読み込めないため変更できません。');
  if(edit.kind==='start-reset'){showStudyStartReset(data.get('startDate'));return;}
  if(edit.kind==='replan'){showReplanPreview(data);return;}
  let candidate;
  if(edit.kind==='replan-preview'||edit.kind==='start-reset-preview'){
   if(edit.date!==today()||localStorage.getItem(KEY)!==edit.raw)throw Error('確認中に日付またはデータが変わりました。条件を変更して、最新の内容でもう一度確認してください。');
   candidate=validate(clonePlanning(edit.candidate));
  }else{
   const raw=localStorage.getItem(KEY);candidate=raw?validate(JSON.parse(raw)):validate(clonePlanning(state));
   if(edit.kind==='weekly')candidate.planner.holidayMinutes=Number(data.get('holidayMinutes'));
   if(edit.kind==='weekly')candidate.planner.weeklyMinutes=Array.from({length:7},(_,i)=>{const v=data.get('day'+i);return v===null||v.trim()===''?null:Number(v);});
   if(edit.kind==='backup')Object.assign(candidate.settings.backup,{enabled:data.has('enabled'),intervalDays:Number(data.get('intervalDays')),snoozedUntil:''});
   validate(candidate);
  }
  persistCompassState(candidate);state=candidate;$('#editor').close();$('#form button[type=submit]').textContent='保存する';render();
 }catch(e){alert('保存できませんでした：'+e.message);}
}
function handlePlanningClick(action){
 if(action==='start-reset-open'){openPlanningEditor('start-reset');return true;}
 if(action==='clear-old-plans'){clearOldPlans();return true;}
 if(action==='restart-study-today'){restartStudyToday();return true;}
 if(action==='weekly-options'){openPlanningEditor('weekly');return true;}
 if(action==='backup-options'){openPlanningEditor('backup');return true;}
 if(action==='replan-open'||action==='replan-back'){if($('#editor').open)$('#editor').close();openPlanningEditor('replan');return true;}
 if(action==='backup-snooze'){
  if(loadFailed)return true;
  try{const raw=localStorage.getItem(KEY),candidate=raw?validate(JSON.parse(raw)):validate(clonePlanning(state));candidate.settings.backup.snoozedUntil=addDays(today(),1);persistCompassState(candidate);state=candidate;render();}catch{alert('通知の延期を保存できませんでした。');}return true;
 }
 return false;
}
function exportCompassBackup(){
 if(loadFailed){alert('読み込みエラーがあるため書き出しを停止しています。元の保存データは変更しません。');return false;}
 if(!confirm('現在のデータをJSONファイルに書き出しますか？'))return false;
 let url;
 try{
  const raw=localStorage.getItem(KEY),candidate=raw?validate(JSON.parse(raw)):validate(clonePlanning(state));
  candidate.settings.backup.lastExported=today();candidate.settings.backup.snoozedUntil='';
  const payload=JSON.stringify(candidate,null,2),link=document.createElement('a');
  url=URL.createObjectURL(new Blob([payload],{type:'application/json'}));link.href=url;link.download=`compass-backup-${today()}-${Date.now()}.json`;document.body.append(link);
  try{link.click();}finally{link.remove();}
  try{persistCompassState(candidate);state=candidate;render();}catch{alert('JSONの書き出しを開始しましたが、最終書き出し日の記録に失敗しました。ダウンロード一覧を確認してください。');}
  return true;
 }catch(e){alert('書き出しできませんでした：'+e.message);return false;}
 finally{if(url)setTimeout(()=>URL.revokeObjectURL(url),1000);}
}

document.addEventListener('DOMContentLoaded',()=>{document.querySelector('#editor').addEventListener('close',()=>{if(!document.querySelector('#editor').open)document.querySelector('#form button[type=submit]').textContent='保存する';});});
function buildStartToday(source,date=today()){
 const candidate=validate(clonePlanning(source));
 const past=candidate.tasks.filter(t=>t.date<date&&['USCPA','IELTS','大学院面接','放送大学'].includes(t.category)&&isReplaceableTask(t,t.date,true));
 const ids=new Set(past.map(t=>t.id));
 candidate.tasks=candidate.tasks.filter(t=>!ids.has(t.id));
 const archive=candidate.planner.beforeStartArchive;
 archive.startDate=date;
 archive.tasks.push(...clonePlanning(past));
 for(const [d,r] of Object.entries(candidate.planner.history))if(d<date&&r.taskIds.some(id=>ids.has(id))){
  archive.history[d]=clonePlanning(r);
  const remaining=r.taskIds.filter(id=>!ids.has(id));
  if(!remaining.length)delete candidate.planner.history[d];
  else {r.taskIds=remaining;r.farTopicIds=inferFarTopicIds(candidate,d);}
 }
 candidate.planner.startDate=date;
 const result=buildReplan(candidate,date,scheduledMinutes(candidate,date),true);
 return {...result,past};
}
function restartStudyToday(){
 if(loadFailed){alert('バックアップの読み込みエラーを解決してください。');return;}
 try{
  const raw=localStorage.getItem(KEY),date=today();
  const result=buildStartToday(raw?validate(JSON.parse(raw)):state,date);
  const names=rows=>rows.map(t=>`${t.name}（${t.minutes}分）`).join('\n')||'なし';
  if(!confirm(`学習開始日を ${date} に変更します。\n\n過去の未完了自動タスクを保管：${result.past.length}件\n${names(result.past)}\n\n今日の自動タスクを置き換え：${result.removed.length}件\n${names(result.removed)}\n\n今日の新しいタスク：${result.added.length}件\n${names(result.added)}\n\n完了実績・手動タスク・編集済み・繰越タスクは保持します。元のタスクは履歴に保管します。この内容で開始しますか？`))return;
  if(today()!==date||localStorage.getItem(KEY)!==raw){alert('データまたは日付が変わりました。もう一度確認してください。');return;}
  persistCompassState(result.candidate);
  state=result.candidate;location.hash='home';render();
 }catch(e){alert('開始日を変更できませんでした。現在のデータは変更していません。');}
}

function buildClearOldPlans(source,date=today()){
 const candidate=validate(clonePlanning(source));
 const removed=candidate.tasks.filter(t=>t.date<=date&&['USCPA','IELTS','大学院面接','放送大学'].includes(t.category)&&isReplaceableTask(t,t.date,true));
 const ids=new Set(removed.map(t=>t.id));
 candidate.tasks=candidate.tasks.filter(t=>!ids.has(t.id));
 candidate.planner.replans=[];
 candidate.planner.beforeStartArchive={startDate:candidate.planner.startDate,tasks:[],history:{}};
 for(const [d,r] of Object.entries(candidate.planner.history)){
  if(d<date)delete candidate.planner.history[d];
  else if(d===date){r.taskIds=r.taskIds.filter(id=>!ids.has(id));r.farTopicIds=inferFarTopicIds(candidate,d);}
 }
 const blockedIds=new Set([...(candidate.planner.history[date]?.taskIds||[]),...candidate.tasks.map(t=>t.id)]);
 const added=buildDailyPlan(candidate,date,{replan:true,blockedIds});candidate.tasks.push(...added);
 candidate.planner.history[date]={version:2,planType:'daily-mixed',taskIds:[...blockedIds,...added.map(t=>t.id)],farTopicIds:inferFarTopicIds(candidate,date),limit:dailyLimit(candidate,date)};
 return {candidate,removed,added};
}
function clearOldPlans(){
 if(loadFailed)return;
 try{
  const raw=localStorage.getItem(KEY),date=today();
  const result=buildClearOldPlans(raw?validate(JSON.parse(raw)):state,date);
  if(!confirm(`古い未着手の自動タスク ${result.removed.length}件と、再配分・開始日前の保管履歴を削除します。今日の予定は設定した開始日で作り直します。\n手動・編集済み・繰越タスクと、現在のタスク一覧にある学習実績は保持します。\nこの内容で整理しますか？`))return;
  if(today()!==date||localStorage.getItem(KEY)!==raw)throw Error('データが変わりました。もう一度操作してください。');
  persistCompassState(result.candidate);state=result.candidate;render();
 }catch(e){alert('整理できませんでした：'+e.message);}
}

// Explicit reset of To Do history; application settings and admissions records stay intact.
function applyStudyStartReset(candidate,date){
 if(!validDate(date))throw Error('開始日を正しく入力してください。');
 const before=t=>t.date<date||(t.autoGenerated&&t.generatedFor<date);
 candidate.tasks=candidate.tasks.filter(t=>!before(t));
 const p=candidate.planner;p.startDate=date;
 p.subjectStarts.far=date;p.subjectStarts.ielts=date;
 p.beforeStartArchive={startDate:date,tasks:[],history:{}};p.replans=[];
 for(const d of Object.keys(p.history))if(d<date)delete p.history[d];
 for(const d of Object.keys(p.dateMinutes))if(d<date)delete p.dateMinutes[d];
 return candidate;
}
function buildStudyStartReset(source,date){
 const candidate=validate(clonePlanning(source));
 const removed=candidate.tasks.filter(t=>t.date<date||(t.autoGenerated&&t.generatedFor<date));
 applyStudyStartReset(candidate,date);
 return {candidate:validate(candidate),removed};
}
function showStudyStartReset(date){
 const raw=localStorage.getItem(KEY),source=raw?validate(JSON.parse(raw)):state;
 const result=buildStudyStartReset(source,date);
 edit={type:'planning-tools',kind:'start-reset-preview',raw,date:today(),...result};
 $('#dialog-title').textContent='開始日前のTo Doを削除';$('#form button[type=submit]').textContent='削除して開始日を設定';
 $('#fields').innerHTML=`<div class="wide"><p>使用開始日：<strong>${esc(date)}</strong></p><p>次の ${result.removed.length}件と保管履歴・再配分履歴を削除します。開始日前には自動タスクを作成しません。</p>${replanTaskRows(result.removed)}<p>指定日以降の予定、大学・試験・科目の設定は保持します。</p></div>`;
}
