'use strict';
const farPlans = {
  'far-review': {label:'Phase 1：高速2周目',tasks:[['text','テキスト・講義復習',180],['mcq','MCQ',90],['mistakes','間違い復習',30]]},
  'far-strengthen': {label:'Phase 2：MCQ・弱点強化',tasks:[['mcq','MCQ',120],['weak','苦手論点復習',90],['tbs','TBS',60],['mistakes','間違い直し',30]]},
  'far-final': {label:'Phase 3：試験直前の復習',tasks:[['mcq','MCQ',120],['weak','弱点の最終確認',120],['mistakes','間違い直し',60]]},
  'far-light': {label:'受験前日：軽い復習',tasks:[['summary','要点・公式の確認',60],['mistakes','間違いノートの見直し',60],['preparation','受験準備と持ち物確認',30]]}
};
const dailyPlanTypes=[...Object.keys(farPlans),'ielts-practice','interview-practice','ouj-study','daily-mixed','far-spaced'];
function inferFarTopicIds(source,date){
  return [...new Set(source.tasks.filter(t=>t.autoGenerated&&t.generatedFor===date&&t.category==='USCPA').flatMap(t=>Array.isArray(t.farTopicIds)?t.farTopicIds:source.far.filter(f=>t.name.split(' · ').slice(1).join(' · ').split(' / ').includes(f.name)).map(f=>f.id)))];
}
function migratePlanner(s){
  if(s.planner===undefined)s.planner={enabled:true,phase:'auto',history:{}};
  const p=s.planner;
  if(!p||typeof p.enabled!=='boolean'||!['auto',...Object.keys(farPlans)].includes(p.phase)||!p.history||typeof p.history!=='object'||Array.isArray(p.history))throw Error('学習プラン設定が不正です');
  if(p.startDate===undefined)p.startDate=today();
  if(!validDate(p.startDate))throw Error('学習開始日が不正です');
  if(p.subjects===undefined)p.subjects={far:true,ielts:true,interview:true,ouj:true};
  for(const key of ['far','ielts','interview','ouj'])if(typeof p.subjects[key]!=='boolean')throw Error('科目設定が不正です');
  for(const [date,r]of Object.entries(p.history)){
    if(!validDate(date)||!r||!dailyPlanTypes.includes(r.planType)||!Array.isArray(r.taskIds)||r.taskIds.some(id=>typeof id!=='string'))throw Error('学習プラン履歴が不正です');
    if(r.farTopicIds===undefined)r.farTopicIds=inferFarTopicIds(s,date);
    if(!Array.isArray(r.farTopicIds)||r.farTopicIds.some(id=>typeof id!=='string')||(r.version!==undefined&&![1,2].includes(r.version)))throw Error('論点選択履歴が不正です');
  }
  for(const t of s.tasks)if(t.autoGenerated!==undefined){
    if(typeof t.autoGenerated!=='boolean'||(t.autoGenerated&&(!dailyPlanTypes.includes(t.planType)||!validDate(t.generatedFor))))throw Error('自動タスク情報が不正です');
    if(t.farTopicIds!==undefined&&(!Array.isArray(t.farTopicIds)||t.farTopicIds.some(id=>typeof id!=='string')))throw Error('自動タスク論点が不正です');
  }
  return migrateStartArchive(migratePlanningTools(migrateSpacedReview(s)));
}
function selectedFarPlan(date=today(),source=state){
  const exam=source.settings.farDate;
  if(!source.planner.subjects.far||!validDate(exam)||date>=exam)return null;
  const remaining=Math.round((parse(exam)-parse(date))/86400000);
  if(remaining===1)return 'far-light';
  if(source.planner.phase!=='auto'&&source.planner.phase!=='far-light')return source.planner.phase;
  return remaining>=34?'far-review':remaining>=18?'far-strengthen':'far-final';
}
function planExists(date=today(),source=state){return Boolean(source.planner.history[date]||source.tasks.some(t=>t.autoGenerated&&t.generatedFor===date));}
function planIsCurrent(date=today(),source=state){return source.planner.history[date]?.version===2;}
function prioritizedFarTopics(source=state,date=today()){
  const used={},rank={C:0,B:1,A:2};
  for(const [d,r]of Object.entries(source.planner.history))if(d<date)for(const id of r.farTopicIds||inferFarTopicIds(source,d))if(!used[id]||used[id]<d)used[id]=d;
  for(const t of source.tasks)if(t.autoGenerated&&t.generatedFor<date)for(const id of t.farTopicIds||inferFarTopicIds(source,t.generatedFor))if(!used[id]||used[id]<t.generatedFor)used[id]=t.generatedFor;
  const yesterday=addDays(date,-1),excluded=new Set([...(source.planner.history[yesterday]?.farTopicIds||[]),...inferFarTopicIds(source,yesterday)]);
  const tier=f=>f.rating==='C'&&!f.last&&!(f.count>0)?0:(rank[f.rating]??0)+1;
  return source.far.filter(f=>!excluded.has(f.id)).sort((a,b)=>tier(a)-tier(b)||(used[a.id]||'').localeCompare(used[b.id]||'')||(a.last||'').localeCompare(b.last||'')||(a.count||0)-(b.count||0)||source.far.indexOf(a)-source.far.indexOf(b));
}
function dailyCommitted(source,date,category){
  return source.tasks.filter(t=>(!category||t.category===category)&&(t.date===date||(t.done&&t.completedDate===date))).reduce((n,t)=>n+(t.date===date?Math.max(t.minutes,t.done&&(t.completedDate||t.date)===date?t.actual:0):t.actual),0);
}
function dailyLimit(source,date=today()){return Math.min(480,scheduledMinutes(source,date),selectedFarPlan(date,source)==='far-light'?150:480);}
function buildDailyPlan(source,date=today(),options={}){
  if(date<source.planner.startDate||(!options.replan&&planIsCurrent(date,source)))return [];
  const existing=!options.replan&&planExists(date,source),type=selectedFarPlan(date,source),light=type==='far-light',groups=[];
  const make=(category,planType,slot,label,minutes,extra={})=>({id:`compass-auto-${date}-${planType}-${slot}`,name:label,category,date,deadline:'',minutes,priority:'中',note:'Daily Planner 自動作成。手動・繰越タスクを含めた残り時間に配分しています。',done:false,actual:0,autoGenerated:true,planType,planSlot:slot,generatedFor:date,...extra});
  const hadCategory=category=>!options.replan&&source.tasks.some(t=>t.autoGenerated&&t.generatedFor===date&&t.category===category);
  // An old daily ledger is upgraded by filling new subjects only; old FAR tasks stay intact.
  if(type&&!existing){
    if(light)groups.push({category:'USCPA',tasks:farPlans[type].tasks.map(([slot,label,minutes])=>make('USCPA',type,slot,`FAR ${label}`,minutes,{deadline:source.settings.farDate,priority:'高',farTopicIds:[],note:'受験前日は新しい章を増やさず、軽い復習と準備に留めます。'}))});
    else {const tasks=farTasksWithReviews(source,date,type,make);if(tasks.length)groups.push({category:'USCPA',tasks});}
  }
  const enabled=source.planner.subjects;
  if(!light&&enabled.ielts&&!hadCategory('IELTS')&&(!source.programs.ielts.examDate||date<source.programs.ielts.examDate)){
    const exam=source.programs.ielts.examDate,near=exam&&Math.round((parse(exam)-parse(date))/86400000)<=14;
    const labels={Speaking:'回答練習',Writing:'構成・ライティング練習',Reading:'読解・復習',Listening:'リスニング・聞き直し'};
    groups.push({category:'IELTS',tasks:source.programs.ielts.skills.map(s=>make('IELTS','ielts-practice',s.name.toLowerCase(),`IELTS ${s.name} · ${near?'本番形式の練習':labels[s.name]}`,30,{deadline:exam||'',note:`${s.weak?'重点：'+s.weak+'。 ':''}目標 ${s.target??source.programs.ielts.target??'未設定'}。${near?'受験2週間以内のため時間を計って練習。':'練習後に苦手な箇所を振り返ります。'}`}))});
  }
  if(!light&&enabled.interview&&!hadCategory('大学院面接')){
    const upcoming=source.universities.filter(u=>u.interviewDate&&u.interviewDate>=date).sort((a,b)=>a.interviewDate.localeCompare(b.interviewDate))[0];
    const questions=[...source.programs.interview.questions].sort((a,b)=>Number(b.university===upcoming?.name)-Number(a.university===upcoming?.name)||(a.count||0)-(b.count||0)||(a.last||'').localeCompare(b.last||''));
    const q=questions[0];
    groups.push({category:'大学院面接',tasks:[make('大学院面接','interview-practice','answer',`大学院面接 · ${q?`${q.university} / ${q.question}`:'自己紹介・志望理由の練習'}`,30,{deadline:upcoming?.interviewDate||'',note:q?`日本語メモ・キーワードを確認し、英語で回答します。質問ID：${q.id}`:'面接画面で大学と質問を登録してください。'})]});
  }
  if(!light&&enabled.ouj&&!hadCategory('放送大学')){
    const active=source.programs.ouj.courses.filter(c=>c.start&&c.start<=date&&c.credits!=='取得済'&&Number(c.progress||0)<100);
    const last=c=>source.tasks.filter(t=>t.autoGenerated&&t.courseId===c.id&&t.generatedFor<date).map(t=>t.generatedFor).sort().at(-1)||'';
    active.sort((a,b)=>last(a).localeCompare(last(b))||(a.deadline||'9999').localeCompare(b.deadline||'9999')||a.name.localeCompare(b.name));
    if(active.length){const c=active[0];groups.push({category:'放送大学',tasks:[make('放送大学','ouj-study','lesson',`放送大学 · ${c.name} / 授業・課題`,30,{courseId:c.id,deadline:c.deadline||'',note:`授業開始日：${c.start}。${c.assignment?'課題：'+c.assignment:'次の授業を進めてください。'}`})]});}
  }
  // Subtract scheduled/manual/carryover time from each subject, then scale to the daily cap.
  const candidates=[];
  for(const g of groups){const desired=g.tasks.reduce((n,t)=>n+t.minutes,0),eligible=g.tasks.filter(t=>!options.blockedIds?.has(t.id)),total=eligible.reduce((n,t)=>n+t.minutes,0),remaining=Math.min(total,Math.max(0,desired-dailyCommitted(source,date,g.category)));if(total)for(const t of eligible)candidates.push({...t,weight:t.minutes*remaining/total});}
  const available=Math.max(0,Math.floor((dailyLimit(source,date)-dailyCommitted(source,date))/5)*5),weight=candidates.reduce((n,t)=>n+t.weight,0),target=Math.min(available,Math.floor(weight/5)*5);
  if(!target||!weight)return [];
  const shares=candidates.map((t,index)=>{const exact=t.weight*target/weight;return {t,index,minutes:Math.floor(exact/5)*5,remainder:exact%5};});
  let rest=target-shares.reduce((n,s)=>n+s.minutes,0);
  for(const share of [...shares].sort((a,b)=>b.remainder-a.remainder||a.index-b.index)){if(rest<5)break;if(share.t.weight>share.minutes){share.minutes+=5;rest-=5;}}
  const result=shares.filter(s=>s.minutes>0).map(({t,minutes})=>{const {weight,...task}=t;return {...task,minutes};});
  for(const t of result)if(t.farStudyChapterId){const chapterTotal=result.filter(x=>x.farStudyChapterId===t.farStudyChapterId).reduce((n,x)=>n+x.minutes,0);t.note=t.note.replace(/本日はこの章に合計[0-9]+分/,`本日はこの章に合計${chapterTotal}分`);}
  for(const t of result)t.autoPlanOriginal=taskPlanSignature(t);
  return result;
}
let plannerError='';
function createDailyPlan(manual=false){
  if(loadFailed){if(manual)alert('既存データの読み込みエラーを解決してから作成してください。');return false;}
  if(!manual&&(!state.planner.enabled||planIsCurrent()))return false;
  try{
    const raw=localStorage.getItem(KEY),source=raw?validate(JSON.parse(raw)):state;
    if(!manual&&!source.planner.enabled){state=source;return false;}
    if(today()<source.planner.startDate){state=source;return false;}
    if(planIsCurrent(today(),source)){state=source;return false;}
    const tasks=buildDailyPlan(source),old=source.planner.history[today()],farTopicIds=[...new Set([...(old?.farTopicIds||inferFarTopicIds(source,today())),...tasks.flatMap(t=>t.farTopicIds||[])])];
    const record={version:2,planType:'daily-mixed',taskIds:[...new Set([...(old?.taskIds||source.tasks.filter(t=>t.autoGenerated&&t.generatedFor===today()).map(t=>t.id)),...tasks.map(t=>t.id)])],farTopicIds,limit:dailyLimit(source)};
    const candidate={...source,tasks:[...source.tasks,...tasks],planner:{...source.planner,history:{...source.planner.history,[today()]:record}}};
    persistCompassState(candidate);state=candidate;plannerError='';return true;
  }catch(e){plannerError='学習プランを保存できませんでした。保存容量またはバックアップデータを確認してください。';if(manual)alert(plannerError);return false;}
}
function planPanel(){
  const limit=dailyLimit(state),committed=dailyCommitted(state,today()),type=selectedFarPlan();
  return `<section class="panel plan-panel"><div class="section-head"><h2>今日の学習プラン</h2><div class="toolbar">${button('generate-plan','今日の学習プランを作成','','primary')}${button('replan-open','今日のプランを再配分')}</div></div>${limit===0?'<p class="muted">今日は休養日です。新しい自動タスクは追加しません。</p>':''}<p class="muted">学習開始日：${esc(state.planner.startDate)}</p><p role="status">${planIsCurrent()?'今日の学習プランは作成済みです':planExists()?'既存プランを保持して不足科目を追加できます':'今日の学習を自動で配分します'}</p><p>${type?esc(farPlans[type].label)+' · ':''}予定・実績確保 ${hours(committed)} / 自動配分の上限 ${hours(limit)}</p>${committed>limit?'<p class="warning">登録済みタスクが上限を超えています。既存タスクは変更していません。必要に応じて時間や実施日を調整してください。</p>':''}<p class="muted">毎日自動作成：${state.planner.enabled?'ON':'OFF'}。通常はFAR 最大5時間・IELTS 2時間・面接30分、開始済みの放送大学30分。手動・繰越分を差し引き、上限内で調整します。受験前日はFARのみ150分以内です。FARは章の残り必要時間に応じて配分し、長い章を複数日に分けます。</p>${plannerError?`<p class="warning">${esc(plannerError)}</p>`:''}</section>`;
}
function plannerSettings(){return `<section class="panel"><h2>受験スケジュール連動</h2><p>学習開始日：${esc(state.planner.startDate)}（この日から毎日のプランを作成）</p>${button('restart-study-today','今日から始め直す')}<p class="muted">過去の未完了自動プランを保管し、今日のプランを再配分します。変更内容を確認してから適用します。</p><label class="checkbox-label"><span><input type="checkbox" id="daily-plan-enabled" ${state.planner.enabled?'checked':''}> 毎日自動で今日の学習プランを作成する</span></label><div class="toolbar">${Object.entries({far:'FAR',ielts:'IELTS',interview:'大学院面接',ouj:'放送大学（授業開始後）'}).map(([key,label])=>`<label><span><input type="checkbox" data-plan-subject="${key}" ${state.planner.subjects[key]?'checked':''}> ${label}</span></label>`).join('')}</div><label>FARの学習段階<select id="daily-plan-phase"><option value="auto" ${state.planner.phase==='auto'?'selected':''}>受験日から自動判定</option>${Object.entries(farPlans).filter(([key])=>key!=='far-light').map(([key,v])=>`<option value="${key}" ${state.planner.phase===key?'selected':''}>${esc(v.label)}</option>`).join('')}</select></label><p class="muted">自動判定：34日以上前は高速2周目、33〜18日前は弱点強化、17〜2日前は直前復習。前日は段階設定にかかわらず全体150分以内。FARとIELTSは登録した受験日当日以降、その科目の新規生成を止めます。</p><p class="muted">未学習Cの論点を1〜2個ずつ順送りし、前日の重点論点は選びません。章の残り必要時間に比例して5分単位で配分し、未完了の予約分は重複生成しません。放送大学は授業開始日以降・進捗100%未満・単位未取得の科目が対象です。全体は8時間または設定目標の小さい方を上限にします。</p><p class="muted">設定変更は次の未作成プランから反映します。今日の変更は「今日のプランを再配分」で確認して適用できます。過去のFARのみのプランは一度だけ不足科目を補完し、既存タスクは保持します。削除・繰越後の同日再作成はありません。</p></section>`;}

// Preserve imported records; never archive them based on a personal fixed date.
function migrateStartArchive(s){
 const p=s.planner;
 if(p.beforeStartArchive===undefined)p.beforeStartArchive={startDate:p.startDate,tasks:[],history:{}};
 const a=p.beforeStartArchive;
 if(!a||!validDate(a.startDate)||!Array.isArray(a.tasks)||a.tasks.some(t=>!t||typeof t.name!=='string'||typeof t.id!=='string')||!a.history||typeof a.history!=='object'||Array.isArray(a.history))throw Error('開始日前の保管履歴が不正です');
 return s;
}
function startArchivePanel(){
 const a=state.planner.beforeStartArchive;
 if(!a?.tasks.length)return '';
 return `<details class="panel"><summary>開始日前の学習履歴（${a.tasks.length}件）</summary><p class="muted">学習開始日 ${esc(a.startDate)} より前の記録です。カレンダー・現在のTo Do・学習時間の集計から外して保管しています。JSONバックアップにも含まれます。</p><ul class="replan-list">${a.tasks.map(t=>`<li><strong>${esc(t.name)}</strong><span>${esc(t.date)} · 予定 ${esc(t.minutes)}分 · ${t.done?'完了':'未完了'} · 実績 ${esc(t.actual)}分</span>${t.note?`<details><summary>メモ</summary><p>${esc(t.note)}</p></details>`:''}</li>`).join('')}</ul></details>`;
}
